# Manual de instrucciones para Render (versión corregida)
services:
  # 1. Definimos el servicio de la base de datos
  - name: condominio-db         # Nombre del servicio
    type: postgres            # CORRECCIÓN: El tipo correcto es 'postgres'
    databaseName: condominio_db # Nombre para la base de datos interna
    user: condominio_user     # Nombre de usuario para la BD
    plan: free                # Usamos el plan gratuito

  # 2. Definimos el servicio de nuestra aplicación web
  - name: condominio-app
    type: web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromService:
          type: postgres # CORRECCIÓN: Debe coincidir con el tipo de la BD
          name: condominio-db
          property: connectionString