# Manual de instrucciones para Render (Blueprint con estructura correcta)

# Primero, definimos todas las bases de datos que necesita el proyecto.
databases:
  - name: condominio-db         # Nombre del servicio de la base de datos
    databaseName: condominio_db   # Nombre para la base de datos interna
    user: condominio_user     # Nombre de usuario para la BD
    plan: free                # Usamos el plan gratuito

# Segundo, definimos todos los servicios web, workers, etc.
services:
  - type: web
    name: condominio-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase: # CORRECCIÓN: Se usa 'fromDatabase' cuando la BD se define arriba
          name: condominio-db
          property: connectionString